

POST http://localhost:3000/register/
Content-Type : application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male"
}



POST http://localhost:3000/login/

Content-Type : application/json
{
  "username": "adam_richard",
  "password": "richard_567"
}
###

GET http://localhost:3000/user/tweets/feed/?limit=4&offset=0&search_q=3859

Authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcyMzk4MDQyMH0.MoV_1vMpUNWJW0QgJatwlyCLfXiTbPGauBTeUCxqnq0

###

GET http://localhost:3000/user/following/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcyMzk2NzQxM30.yhTMwQRx9Ztq3C1zZPa6gv-L3z3qnkpafnYPWaATwaw

###

GET http://localhost:3000/user/followers/
Authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcyMzk2MjYwMX0.qX9_i4zGfOuuQJoSQ9v5bfWYywThfWL97jg-GpbVDQk

GET http://localhost:3000/tweets/5/
Authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcyMzk2OTkwMX0.TmM4Bpspg9IrsusWQECX3HO6in1Kcvm9jDV5uvc6AmQ


GET http://localhost:3000/tweets/5/likes/
Authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcyMzk2OTkwMX0.TmM4Bpspg9IrsusWQECX3HO6in1Kcvm9jDV5uvc6AmQ


GET http://localhost:3000/tweets/5/replies/
Authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcyMzk2OTkwMX0.TmM4Bpspg9IrsusWQECX3HO6in1Kcvm9jDV5uvc6AmQ


GET http://localhost:3000/user/tweets/
Authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcyMzk2OTkwMX0.TmM4Bpspg9IrsusWQECX3HO6in1Kcvm9jDV5uvc6AmQ


POST http://localhost:3000/user/tweets/
Authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcyMzk2OTkwMX0.TmM4Bpspg9IrsusWQECX3HO6in1Kcvm9jDV5uvc6AmQ

Content-Type : application/json
{
   "tweet": "The Mornings",
    "userId":5,
    "dateTime": "2021-4-3 08:32:44"
}

DELETE http://localhost:3000/tweets/5/
Authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW1fcmljaGFyZCIsImlhdCI6MTcyMzk4MDE3N30.RO0kssiFxwhZPnfnWIiWQfwT1R3SkJYG9RsZrPZMvpc

